chore: 2024 update

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -2,10 +2,13 @@ name: ci
 
 on:
   push:
-    branches: [master]
-    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
+    branches:
+      - master
+    tags:
+      - v*
   pull_request:
-    branches: [master]
+    branches:
+      - master
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
@@ -16,25 +19,44 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Check Git tag format
+        if: startsWith(github.ref_name, 'v')
+        env:
+          THESIS_TAG: ${{ github.ref_name }}
+        run: |
+          _tag="$THESIS_TAG"
+          if ! printf "%s\n" "$_tag" | grep -q -P '^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-(alpha|beta|rc)\.(0|[1-9][0-9]*))?$'; then
+            printf '[ERROR]: Git tag (%s) wrong format\n' "$_tag"
+            exit 1
+          fi
+
       - name: Install TeX Live
-        uses: teatimeguest/setup-texlive-action@v2
+        uses: teatimeguest/setup-texlive-action@v3
         with:
           packages: >-
             scheme-full
+
       - name: Setup Node.js
-        uses: actions/setup-node@v3
+        uses: actions/setup-node@v4
         with:
-          node-version: 18
+          node-version: 20
+
       - name: Install dependencies
         run: |
           npm ci
+
       - name: Check
         run: |
           npm run check
+
       - name: Compile
         run: |
           npm run build
+
       - name: Release
         uses: marvinpinto/action-automatic-releases@latest
         if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v'))
@@ -45,4 +67,4 @@ jobs:
           title: ${{ startsWith(github.ref , 'refs/tags/v') && github.ref_name || 'Nightly' }}
           files: |
             LICENSE
-            surname_name_computer_science_2022_2023.pdf
+            surname_name_computer_science_2023_2024.pdf
